### ISSUE TITLE
Aplication schematics and defining interfaces

### ISSUE THREAD

**Issue by jb88Julia** [AnotherGoose/Multi-Sensors-Fusion-for-High-Resolution-3D-Lidar-videos#1]
Let's figure out (or sum up) the way our codes are going to go together, what data is going to be passed from one code to another, what format, what size etc...? 

I think we should have it written down somewhere, so started this issue.
Someone mentioned there is some schematics done?

**Comment by AnotherGoose** [comment]
I believe we had agreed on adapting the folder structure we have now, with added folders for passing depth maps between models.
It probably takes the form of a to be a top-level folder called "InputDepth" and "InputRGB", which would be used by the adaptive sampling methods and output into a folder called "SampledDepth", this would be used as the input for the denoising models. Then there would be a folder called "DenoisedDepth", which is the output from the denoising models, which finally would be used by the super-resolution methods, the output for which would be shot into a folder called "Super-ResolvedDepth."

This application would mean we wouldn't have to join models together (In terms of code), and a script is required to control the flow calling each model, taking inputs from the respective folders.
 
These names aren't set in stone, and I would like peoples to opinion on this approach.

**Comment by AnotherGoose** [comment]
> 
> 
> I believe we had agreed on adapting the folder structure we have now, with added folders for passing depth maps between models.
> It probably takes the form of a to be a top-level folder called "InputDepth" and "InputRGB", which would be used by the adaptive sampling methods and output into a folder called "SampledDepth", this would be used as the input for the denoising models. Then there would be a folder called "DenoisedDepth", which is the output from the denoising models, which finally would be used by the super-resolution methods, the output for which would be shot into a folder called "Super-ResolvedDepth."
> 
> This application would mean we wouldn't have to join models together (In terms of code), and a script is required to control the flow calling each model, taking inputs from the respective folders.
> 
> These names aren't set in stone, and I would like peoples to opinion on this approach.

Once we have settled on a design I could place it in the readme as a diagram

**Comment by jb88Julia** [comment]
I like the idea of not having to merge the code and having a framework working on it. 

What I mean by passing on data is stuff like size (width, height of the image), format (.mat, .png ...?) and dimentions (m, mm?).

**Comment by AnotherGoose** [comment]
> 
> 
> I like the idea of not having to merge the code and having a framework working on it.
> 
> What I mean by passing on data is stuff like size (width, the height of the image), format (.mat, .png ...?) and dimensions (m, mm?).

It should be in a .png format and shouldn't your code auto handle an image of any size, we can ask Halimi about the size of the image we would be expected to handle.

**Comment by jb88Julia** [comment]
Yeah, I'm going to try to make my code handle all sizes. Idk about the guys tho
